## Basic Configuration

baseurl = "upasanasen.github.io"
builddrafts = false
canonifyurls = false
languagecode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Upasana Sen"
title = "Upasana Sen"

theme = "manis"


# Copyright notice. Note: You can use HTML tag here
copyright = "&copy; 2019 Upasana Sen <a href=\"http://creativecommons.org/licenses/by/3.0/\">Some Rights Reserved</a>."
pluralizeListTitles = false

# Minimum number of posts before paginate navigation show up
paginate = 10

# Code Highlighting (Chroma)
pygmentsCodeFences = true
pygmentsUseClasses = true

[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 100
    url = "/about"
[[menu.main]]
    name = "blog"
    identifier = "blog"
    weight = 200
    url = "/blog/"


[taxonomies]
	tag = "tags"



## Site Settings
[params]
    author = "Upasana Sen"
    intro = "Environmental Studies and Sustainability Science master student at Lund University"
    description = "Sweet little Hugo's theme for personal website or blog."
    authorimage = "headshot.jpg"
    dateformat = "Jan 2, 2006"

    tagline = "random tidbits"
    #keywords = ""

    # If true give attribution to this theme
	themeAttrib = true

	# URL to license file, can be outside of your domain
	#licenseURL = "/about/license"

	# Configure which sections for Latest Posts
	mainSections = ["blog"]

	# Configure which sections for Latest Works
	#workSections = ["projects"]

	# List of sections that support disqus comments
	disqusSections = [ "blog" ]

	# List of sections that support utterances comments
	utterancesSections = [ "blog" ]

	# Utterances Configuration
	utterancesRepo = ""
	utterancesTheme = "github-light"
	utterancesLabel = ""

	# 404 Configuration
	head404 = "Sorry, I can't find what you want."
	sub404 = "Back to <a href='/'>Home</a>."

	# Color of your website's accent
	#colorTheme = "#ff6565"

	# Maximum number of item in Latest Posts or Works
	latestCount = 5

	# Path to site's favicon image  (path: /static/images/headshot.jpg replace there)
	faviconImg = "images/headshot.jpg"

	# Code Highlighting (HighlightJS)
	highlightJs = false
	highlightJsLanguages = [ "go" ]
	highlightJsStyle = "ocean"

    github = "upasanasen"
    linkedin = "upasana-sen-693830104"
    email = "upasana19sen95@gmail.com"

## Main Menu
#[[menu.main]]
#    name = "resume"
#    identifier = "resume"
#    weight = 100
#    url = "/resume.pdf"
#[[menu.main]]
#    name = "projects"
#    identifier = "projects"
#    weight = 200
#    url = "/projects/"




